# Generated by Django 3.0.4 on 2020-11-08 20:17

from django.db import migrations, models
import taxes.receipts.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_june_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendoraliaspattern',
            name='pattern',
            field=models.CharField(db_index=True, max_length=200, unique=True, validators=[taxes.receipts.models.models.validate_uppercase]),
        ),
    ]
