# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exclusioncondition',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exclusioncondition',
            name='prefix',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='fixed_amount',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
