# Generated by Django 3.0.7 on 2021-02-16 00:23

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_alias_pattern_uppercase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='expense_type',
            field=models.CharField(choices=[('ignore', '*IGNORE*'), ('administrative', 'Management and Administrative'), ('advertising', 'Advertising'), ('capital_gains', 'Capital Gains'), ('donation', 'Donations'), ('foreign_income', 'Foreign Income'), ('hoa_fees', 'HOA Fees'), ('interest', 'Interest'), ('insurance', 'Insurance'), ('maintenance', 'Repair and Maintenance'), ('meals', 'Meals'), ('property_tax', 'Property Tax'), ('rent', 'Gross Rent'), ('supplies', 'Office Supplies'), ('telephone', 'Telephone'), ('travel', 'Business Travel'), ('utility', 'Utilities')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='default_expense_type',
            field=models.CharField(blank=True, choices=[('ignore', '*IGNORE*'), ('administrative', 'Management and Administrative'), ('advertising', 'Advertising'), ('capital_gains', 'Capital Gains'), ('donation', 'Donations'), ('foreign_income', 'Foreign Income'), ('hoa_fees', 'HOA Fees'), ('interest', 'Interest'), ('insurance', 'Insurance'), ('maintenance', 'Repair and Maintenance'), ('meals', 'Meals'), ('property_tax', 'Property Tax'), ('rent', 'Gross Rent'), ('supplies', 'Office Supplies'), ('telephone', 'Telephone'), ('travel', 'Business Travel'), ('utility', 'Utilities')], db_index=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='vendoraliaspattern',
            name='default_expense_type',
            field=models.CharField(blank=True, choices=[('ignore', '*IGNORE*'), ('administrative', 'Management and Administrative'), ('advertising', 'Advertising'), ('capital_gains', 'Capital Gains'), ('donation', 'Donations'), ('foreign_income', 'Foreign Income'), ('hoa_fees', 'HOA Fees'), ('interest', 'Interest'), ('insurance', 'Insurance'), ('maintenance', 'Repair and Maintenance'), ('meals', 'Meals'), ('property_tax', 'Property Tax'), ('rent', 'Gross Rent'), ('supplies', 'Office Supplies'), ('telephone', 'Telephone'), ('travel', 'Business Travel'), ('utility', 'Utilities')], db_index=True, max_length=14, null=True),
        ),
    ]
