# Generated by Django 3.0.7 on 2021-03-08 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_refactor_expensetype'),
    ]

    forwards_sql = """
    UPDATE vendor
    SET default_asset_id = assigned_asset_id
    WHERE assigned_asset_id IS NOT NULL;

    UPDATE vendor_alias_pattern aliases
    SET default_asset_id = matched_alias.assigned_asset_id
    FROM (
        SELECT aliases.id AS id, vendor.assigned_asset_id AS assigned_asset_id
        FROM vendor_alias_pattern aliases
        JOIN vendor ON (aliases.vendor_id = vendor.id)
        WHERE vendor.assigned_asset_id IS NOT NULL
    ) AS matched_alias
    WHERE aliases.id = matched_alias.id;

    UPDATE receipt
    SET asset_id = matched_transaction.assigned_asset_id
    FROM (
        SELECT receipt.id AS id, vendor.assigned_asset_id AS assigned_asset_id
        FROM receipt
        JOIN vendor ON (receipt.vendor_id = vendor.id)
        WHERE vendor.assigned_asset_id IS NOT NULL
    ) AS matched_transaction
    WHERE receipt.id = matched_transaction.id;
    """

    reverse_sql = """
    UPDATE vendor
    SET assigned_asset_id = default_asset_id
    WHERE default_asset_id IS NOT NULL;
    """

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='asset',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='receipts.FinancialAsset'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='default_asset',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='receipts.FinancialAsset'),
        ),
        migrations.AddField(
            model_name='vendoraliaspattern',
            name='default_asset',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='receipts.FinancialAsset'),
        ),
        migrations.RunSQL(forwards_sql, reverse_sql=reverse_sql, elidable=True),
        migrations.RemoveField(
            model_name='vendor',
            name='assigned_asset',
        ),
    ]
