# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-06 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import taxes.receipts.types
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_auto_20170708_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAsset',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('type', enumfields.fields.EnumField(enum=taxes.receipts.types.FinancialAssetType, max_length=14)),
            ],
            options={
                'db_table': 'financial_asset',
            },
        ),
        migrations.RemoveField(
            model_name='vendorsite',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='VendorSite',
        ),
        migrations.AddField(
            model_name='vendor',
            name='assigned_asset',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_vendors', to='receipts.FinancialAsset'),
        ),
    ]
