# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-13 07:43
# flake8: noqa: E501
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0004_auto_20170806_0245'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForexRate',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pair', models.CharField(max_length=8)),
                ('effective_at', models.DateField(db_index=True)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'db_table': 'forex_rate',
            },
        ),
        migrations.AlterUniqueTogether(
            name='forexrate',
            unique_together=set([('pair', 'effective_at')]),
        ),
    ]
