# Generated by Django 2.0.1 on 2018-01-06 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0005_auto_20171113_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodicpayment',
            name='vendor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='receipts.Vendor'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='receipts.PaymentMethod'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_receipts',
                                    to='receipts.Vendor'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='assigned_asset',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='assigned_vendors', to='receipts.FinancialAsset'),
        ),
    ]
