# Generated by Django 3.0.7 on 2021-04-18 19:13

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Transaction = apps.get_model('receipts', 'transaction')
    db_alias = schema_editor.connection.alias
    Transaction.objects.using(db_alias).update(transaction_type=models.F('expense_type'))


def reverse_func(apps, schema_editor):
    Transaction = apps.get_model('receipts', 'transaction')
    db_alias = schema_editor.connection.alias
    Transaction.objects.using(db_alias).update(expense_type=models.F('transaction_type'))


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0005_license_expense_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('ignore', '*IGNORE*'), ('administrative', 'Management and Administrative'), ('advertising', 'Advertising'), ('bank', 'Bank Charges'), ('capital_gains', 'Capital Gains'), ('donation', 'Donations'), ('foreign_income', 'Foreign Income'), ('hoa_fees', 'HOA Fees'), ('interest', 'Interest'), ('insurance', 'Insurance'), ('lease', 'Lease Fees'), ('maintenance', 'Repair and Maintenance'), ('meals', 'Meals'), ('professional_services', 'Professional Services'), ('property_tax', 'Property Tax'), ('rent', 'Gross Rent'), ('revenue', 'Gross Revenue'), ('supplies', 'Office Supplies'), ('taxes', 'Taxes'), ('telephone', 'Telephone'), ('travel', 'Business Travel'), ('utility', 'Utilities'), ('license', 'Taxes and Licenses')], max_length=21, null=True),
        ),
        migrations.RunPython(forwards_func, reverse_func),
        migrations.RemoveField(
            model_name='transaction',
            name='expense_type',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='default_expense_type',
            field=models.CharField(blank=True, choices=[('ignore', '*IGNORE*'), ('administrative', 'Management and Administrative'), ('advertising', 'Advertising'), ('bank', 'Bank Charges'), ('capital_gains', 'Capital Gains'), ('donation', 'Donations'), ('foreign_income', 'Foreign Income'), ('hoa_fees', 'HOA Fees'), ('interest', 'Interest'), ('insurance', 'Insurance'), ('lease', 'Lease Fees'), ('maintenance', 'Repair and Maintenance'), ('meals', 'Meals'), ('professional_services', 'Professional Services'), ('property_tax', 'Property Tax'), ('rent', 'Gross Rent'), ('revenue', 'Gross Revenue'), ('supplies', 'Office Supplies'), ('taxes', 'Taxes'), ('telephone', 'Telephone'), ('travel', 'Business Travel'), ('utility', 'Utilities'), ('license', 'Taxes and Licenses')], db_index=True, max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='vendoraliaspattern',
            name='default_expense_type',
            field=models.CharField(blank=True, choices=[('ignore', '*IGNORE*'), ('administrative', 'Management and Administrative'), ('advertising', 'Advertising'), ('bank', 'Bank Charges'), ('capital_gains', 'Capital Gains'), ('donation', 'Donations'), ('foreign_income', 'Foreign Income'), ('hoa_fees', 'HOA Fees'), ('interest', 'Interest'), ('insurance', 'Insurance'), ('lease', 'Lease Fees'), ('maintenance', 'Repair and Maintenance'), ('meals', 'Meals'), ('professional_services', 'Professional Services'), ('property_tax', 'Property Tax'), ('rent', 'Gross Rent'), ('revenue', 'Gross Revenue'), ('supplies', 'Office Supplies'), ('taxes', 'Taxes'), ('telephone', 'Telephone'), ('travel', 'Business Travel'), ('utility', 'Utilities'), ('license', 'Taxes and Licenses')], db_index=True, max_length=21, null=True),
        ),
    ]
