# Generated by Django 3.0.14 on 2021-05-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0006_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='allow_periodic_payments',
            field=models.BooleanField(default=False),
        ),
    ]
