# Generated by Django 2.0.1 on 2018-04-15 01:33

from django.db import migrations
import enumfields.fields
import taxes.receipts.types


def _forward_move_tax_adjustment_type(apps, schema_editor):
    PeriodicPayment = apps.get_model('receipts', 'PeriodicPayment')
    db_alias = schema_editor.connection.alias

    periodic_payments_with_adjustments = PeriodicPayment.objects.using(db_alias).filter(
        tax_adjustment_type__isnull=False,
    )
    for periodic_payment in periodic_payments_with_adjustments:
        periodic_payment.vendor.tax_adjustment_type = periodic_payment.tax_adjustment_type
        periodic_payment.vendor.save()


def _reverse_move_tax_adjustment_type(apps, schema_editor):
    Vendor = apps.get_model('receipts', 'Vendor')
    db_alias = schema_editor.connection.alias

    vendors_with_adjustments = Vendor.objects.using(db_alias).filter(
        tax_adjustment_type__isnull=False,
    )
    for vendor in vendors_with_adjustments:
        vendor.periodic_payment.tax_adjustment_type = vendor.tax_adjustment_type
        vendor.periodic_payment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0007_auto_20180221_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='tax_adjustment_type',
            field=enumfields.fields.EnumField(blank=True, enum=taxes.receipts.types.TaxTypeEnum,
                                              max_length=3, null=True),
        ),
        migrations.RunPython(
            _forward_move_tax_adjustment_type,
            _reverse_move_tax_adjustment_type,
            elidable=True
        ),
        migrations.RemoveField(
            model_name='periodicpayment',
            name='tax_adjustment_type',
        ),
    ]
