# Generated by Django 2.0.1 on 2018-04-15 06:54

from django.db import migrations


def _invert_forex_pairs(apps, schema_editor):
    """
    Invert currency pair labels since it was backwards
    """
    ForexRate = apps.get_model('receipts', 'ForexRate')
    db_alias = schema_editor.connection.alias

    # amount of data is small (~300 rows), acceptable to do this row by row
    for rate in ForexRate.objects.using(db_alias).all():
        pair_components = rate.pair.split('/')
        rate.pair = '/'.join(reversed(pair_components))
        rate.save()


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0008_auto_20180415_0133'),
    ]

    operations = [
        migrations.RunPython(_invert_forex_pairs, _invert_forex_pairs, elidable=True)
    ]
