# Generated by Django 2.0.1 on 2018-06-09 22:43

from django.db import migrations
import enumfields.fields
import taxes.receipts.types


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0010_expense_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendoraliaspattern',
            name='default_expense_type',
            field=enumfields.fields.EnumField(blank=True, db_index=True, enum=taxes.receipts.types.ExpenseType, max_length=14, null=True),
        ),
    ]
