# Generated by Django 2.0.1 on 2018-06-10 01:25

from django.db import migrations
import enumfields.fields
import taxes.receipts.constants


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0011_vendoraliaspattern_default_expense_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialasset',
            name='type',
            field=enumfields.fields.EnumField(enum=taxes.receipts.constants.FinancialAssetType, max_length=17),
        ),
    ]
