# Generated by Django 2.0.1 on 2018-08-14 23:10
# pylint: disable=invalid-name
from django.db import migrations
import taxes.receipts.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0012_asset_primaryresidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialasset',
            name='type',
            field=taxes.receipts.models.fields.TaxesEnumField(
                enum='taxes.receipts.constants.FinancialAssetType'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='currency',
            field=taxes.receipts.models.fields.TaxesEnumField(
                enum='taxes.receipts.constants.Currency'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='type',
            field=taxes.receipts.models.fields.TaxesEnumField(
                enum='taxes.receipts.constants.PaymentMethod'),
        ),
        migrations.AlterField(
            model_name='periodicpayment',
            name='currency',
            field=taxes.receipts.models.fields.TaxesEnumField(
                enum='taxes.receipts.constants.Currency'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='currency',
            field=taxes.receipts.models.fields.TaxesEnumField(
                enum='taxes.receipts.constants.Currency'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='expense_type',
            field=taxes.receipts.models.fields.TaxesEnumField(
                enum='taxes.receipts.constants.ExpenseType'),
        ),
        migrations.AlterField(
            model_name='taxadjustment',
            name='tax_type',
            field=taxes.receipts.models.fields.TaxesEnumField(
                enum='taxes.receipts.constants.TaxType'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='default_expense_type',
            field=taxes.receipts.models.fields.TaxesEnumField(
                blank=True, db_index=True,
                enum='taxes.receipts.constants.ExpenseType', null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='tax_adjustment_type',
            field=taxes.receipts.models.fields.TaxesEnumField(
                blank=True,
                enum='taxes.receipts.constants.TaxType', null=True),
        ),
        migrations.AlterField(
            model_name='vendoraliaspattern',
            name='default_expense_type',
            field=taxes.receipts.models.fields.TaxesEnumField(
                blank=True, db_index=True,
                enum='taxes.receipts.constants.ExpenseType', null=True),
        ),
        migrations.AlterField(
            model_name='vendoraliaspattern',
            name='match_operation',
            field=taxes.receipts.models.fields.TaxesEnumField(
                db_index=True, default='like',
                enum='taxes.receipts.constants.AliasMatchOperation'),
        ),
    ]
