# Generated by Django 2.0.1 on 2019-03-13 06:20

from django.db import migrations, models
import taxes.receipts.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0012_asset_primaryresidence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxadjustment',
            options={'ordering': ('receipt__transaction_date', 'receipt__vendor__name', 'tax_type')},
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='purchased_at',
            new_name='transaction_date',
        ),
        migrations.AlterField(
            model_name='exclusioncondition',
            name='prefix',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, validators=[taxes.receipts.models.models.validate_uppercase]),
        ),
    ]
