# Generated by Django 2.0.1 on 2019-03-13 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0013_auto_20190313_0620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialasset',
            old_name='type',
            new_name='asset_type',
        ),
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='type',
            new_name='method_type',
        ),
    ]
