# Generated by Django 2.0.1 on 2019-04-22 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0014_auto_20190313_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='file_prefix',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='parser_class',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
