# Generated by Django 2.2.2 on 2019-06-07 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0015_auto_20190422_0503'),
    ]

    operations = [
        migrations.RenameModel('Receipt', 'Transaction')
    ]
