# Generated by Django 3.0.4 on 2020-06-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0018_auto_20190610_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialasset',
            name='asset_type',
            field=models.CharField(choices=[('rental', 'Rental'), ('employment', 'Employment'), ('proprietorship', 'Proprietorship'), ('primary_residence', 'Primary Residence')], max_length=17),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('CAD', 'CAD')], max_length=3),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='method_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card')], max_length=11),
        ),
        migrations.AlterField(
            model_name='periodicpayment',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('CAD', 'CAD')], max_length=3),
        ),
        migrations.AlterField(
            model_name='taxadjustment',
            name='tax_type',
            field=models.CharField(choices=[('hst', 'HST')], max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('CAD', 'CAD')], max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='expense_type',
            field=models.CharField(choices=[('ignore', '*IGNORE*'), ('property_tax', 'Property Tax'), ('interest', 'Interest'), ('insurance', 'Insurance'), ('utility', 'Telephone and Utilities'), ('administrative', 'Management and Administrative'), ('maintenance', 'Repair and Maintenance'), ('travel', 'Business Travel'), ('meals', 'Meals and Entertainment'), ('supplies', 'Office Supplies'), ('rent', 'Gross Rent'), ('foreign_income', 'Foreign Income'), ('capital_gains', 'Capital Gains'), ('advertising', 'Advertising'), ('donation', 'Donations')], max_length=23, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='default_expense_type',
            field=models.CharField(blank=True, choices=[('ignore', '*IGNORE*'), ('property_tax', 'Property Tax'), ('interest', 'Interest'), ('insurance', 'Insurance'), ('utility', 'Telephone and Utilities'), ('administrative', 'Management and Administrative'), ('maintenance', 'Repair and Maintenance'), ('travel', 'Business Travel'), ('meals', 'Meals and Entertainment'), ('supplies', 'Office Supplies'), ('rent', 'Gross Rent'), ('foreign_income', 'Foreign Income'), ('capital_gains', 'Capital Gains'), ('advertising', 'Advertising'), ('donation', 'Donations')], db_index=True, max_length=23, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='tax_adjustment_type',
            field=models.CharField(blank=True, choices=[('hst', 'HST')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='vendoraliaspattern',
            name='default_expense_type',
            field=models.CharField(blank=True, choices=[('ignore', '*IGNORE*'), ('property_tax', 'Property Tax'), ('interest', 'Interest'), ('insurance', 'Insurance'), ('utility', 'Telephone and Utilities'), ('administrative', 'Management and Administrative'), ('maintenance', 'Repair and Maintenance'), ('travel', 'Business Travel'), ('meals', 'Meals and Entertainment'), ('supplies', 'Office Supplies'), ('rent', 'Gross Rent'), ('foreign_income', 'Foreign Income'), ('capital_gains', 'Capital Gains'), ('advertising', 'Advertising'), ('donation', 'Donations')], db_index=True, max_length=23, null=True),
        ),
        migrations.AlterField(
            model_name='vendoraliaspattern',
            name='match_operation',
            field=models.CharField(choices=[('equal', 'Equal'), ('like', 'Like')], db_index=True, default='like', max_length=5),
        ),
    ]
