repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: a193eab99ed99429b9b8e517be68bed9a7f6ec4f
  hooks:
  - id: flake8
    args: ["--config=.flake8"]
    # Required due to pre-commit-hooks bug #112
    # https://github.com/pre-commit/pre-commit-hooks/issues/112
    exclude: 'taxes/receipts/migrations'

- repo: git://github.com/pre-commit/mirrors-pylint
  rev: v1.9.1
  hooks:
  - id: pylint
    entry: pylint
    args: ["--rcfile=.pylintrc"]
    additional_dependencies: [pylint_django, django, django-enumfields]
