DATABASE_URI: "sqlite://:memory:"
DEBUG: false,
EXCLUSION_FILTER_MODULES: ["taxes.receipts.filters"]
LOGGING:
  version: 1
  disable_existing_loggers: true
  formatters:
    default:
      format: "%(levelname)s %(message)s"
  handlers:
    console:
      level: INFO
      class: logging.StreamHandler
      formatter: default
  loggers:
    taxes.receipts:
      level: DEBUG
      handlers: ["console"]
      formatter: default
    django.db.backends:
      level: DEBUG
      handlers: ["console"]
      formatter: default
SPREADSHEET:
  id: "<Google spreadsheet id goes here>",
  credentials_file: path/to/secrets/gdrive.json
